[package]
name = "humanCAST"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
eframe = "0.32.2"
egui = "0.32.2"
egui-plotter = "0.6.0"
tokio = { version = "1.47.1", features = ["full"] }
